version: '3.8'

services:
  nginx-php-test:
    container_name: nginx-php-test
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ../:/var/www/html:delegated
      - ./nginx/hosts:/etc/nginx/conf.d:delegated
    links:
      - php-test
    networks:
      - default_network

  php-test:
    container_name: php-test
    image: carlonicora/php-test:1.0
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      target: ${ENVIRONMENT}
      args:
        - XDEBUG_HOST=${XDEBUG_HOST}
        - XDEBUG_PORT=${XDEBUG_PORT}
    volumes:
      - ../:/var/www/html:delegated
    networks:
      - default_network

  mysql-php-test:
    image: mysql:8.0.22
    container_name: mysql-php-test
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - ./../db:/var/lib/mysql:delegated
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: carlonicora